-- CFPB Complaint Operations Analytics | Snowflake setup
-- Run with a role allowed to create a warehouse, database, schemas, role, and user grants.
-- Cost guardrail: the warehouse is X-Small and suspends after 60 seconds of inactivity.

CREATE OR REPLACE WAREHOUSE CFPB_PORTFOLIO_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Portfolio-only warehouse for CFPB complaint operations analytics';

CREATE OR REPLACE DATABASE CFPB_ANALYTICS
  COMMENT = 'CFPB Complaint Operations Analytics portfolio database';

CREATE OR REPLACE SCHEMA CFPB_ANALYTICS.RAW
  COMMENT = 'Privacy-minimized landing table; no narratives, ZIP codes, or tags';

CREATE OR REPLACE SCHEMA CFPB_ANALYTICS.ANALYTICS
  COMMENT = 'dbt-built dimensions, fact table, and Tableau-ready marts';

CREATE OR REPLACE ROLE CFPB_PORTFOLIO_ROLE;

-- The setup is first run as ACCOUNTADMIN. Give the currently signed-in owner the
-- project role so subsequent dbt work does not continue under ACCOUNTADMIN.
SET CFPB_PORTFOLIO_CURRENT_USER = CURRENT_USER();
GRANT ROLE CFPB_PORTFOLIO_ROLE TO USER IDENTIFIER($CFPB_PORTFOLIO_CURRENT_USER);

GRANT USAGE ON WAREHOUSE CFPB_PORTFOLIO_WH TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT USAGE ON DATABASE CFPB_ANALYTICS TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA CFPB_ANALYTICS.RAW TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA CFPB_ANALYTICS.ANALYTICS TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA CFPB_ANALYTICS.RAW TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA CFPB_ANALYTICS.RAW TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CFPB_ANALYTICS.ANALYTICS TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CFPB_ANALYTICS.ANALYTICS TO ROLE CFPB_PORTFOLIO_ROLE;

CREATE OR REPLACE FILE FORMAT CFPB_ANALYTICS.RAW.CFPB_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ESCAPE_UNENCLOSED_FIELD = NONE
  NULL_IF = ('', 'NULL')
  EMPTY_FIELD_AS_NULL = TRUE
  COMPRESSION = AUTO;

CREATE OR REPLACE STAGE CFPB_ANALYTICS.RAW.CFPB_LOCAL_STAGE
  FILE_FORMAT = CFPB_ANALYTICS.RAW.CFPB_CSV_FORMAT
  COMMENT = 'Temporary local upload stage; remove staged files after a successful load';

GRANT USAGE ON FILE FORMAT CFPB_ANALYTICS.RAW.CFPB_CSV_FORMAT TO ROLE CFPB_PORTFOLIO_ROLE;
GRANT READ, WRITE ON STAGE CFPB_ANALYTICS.RAW.CFPB_LOCAL_STAGE TO ROLE CFPB_PORTFOLIO_ROLE;

-- Source file positions 9 (ZIP code) and 10 (tags) are intentionally not loaded.
-- Consumer complaint narratives are never present in the source extract used here.
CREATE OR REPLACE TABLE CFPB_ANALYTICS.RAW.COMPLAINTS_CSV (
  DATE_RECEIVED_RAW VARCHAR,
  PRODUCT_RAW VARCHAR,
  SUB_PRODUCT_RAW VARCHAR,
  ISSUE_RAW VARCHAR,
  SUB_ISSUE_RAW VARCHAR,
  COMPANY_PUBLIC_RESPONSE_RAW VARCHAR,
  COMPANY_RAW VARCHAR,
  STATE_RAW VARCHAR,
  SUBMITTED_VIA_RAW VARCHAR,
  DATE_SENT_TO_COMPANY_RAW VARCHAR,
  COMPANY_RESPONSE_TO_CONSUMER_RAW VARCHAR,
  TIMELY_RESPONSE_RAW VARCHAR,
  COMPLAINT_ID_RAW VARCHAR,
  YEAR_RAW VARCHAR,
  MONTH_START_RAW VARCHAR,
  HAS_COMPANY_RESPONSE_RAW VARCHAR,
  TIMELY_RESPONSE_FLAG_RAW VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'CFPB 2023-2025 prepared extract. Excludes consumer narratives, ZIP codes, and tags.';
